### ISSUE TITLE
Package no longer working with pydantic 2.0

### ISSUE THREAD

**Issue by sdrobert** [zerospeech/benchmarks#28]
Hi Nick,

When I re-installed my environment and tried running `zrc init`, I got the following error.

``` python
  File "/xxx/python3.10/site-packages/zerospeech/model/datasets.py", line 6, in <module>
    from pydantic.generics import GenericModel
ImportError: cannot import name 'GenericModel' from 'pydantic.generics' (/xxx/python3.10/site-packages/pydantic/generics.py)
```

I think this is due to breaking changes in the newly-released Pydantic 2.0. Adding the constraint `pydantic<2` in my environment fixed the problem for me.

Thanks,
Sean

**Comment by nhamilakis** [comment]
Thanks for pointing it out, I updated the requirements.txt to reflect this constraint.
